// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MachineLearningProjektML.Model
{
    public class ModelInput
    {
        [ColumnName("car"), LoadColumn(0)]
        public string Car { get; set; }


        [ColumnName("price"), LoadColumn(1)]
        public float Price { get; set; }


        [ColumnName("body"), LoadColumn(2)]
        public string Body { get; set; }


        [ColumnName("mileage"), LoadColumn(3)]
        public float Mileage { get; set; }


        [ColumnName("engV"), LoadColumn(4)]
        public float EngV { get; set; }


        [ColumnName("engType"), LoadColumn(5)]
        public string EngType { get; set; }


        [ColumnName("registration"), LoadColumn(6)]
        public string Registration { get; set; }


        [ColumnName("year"), LoadColumn(7)]
        public float Year { get; set; }


        [ColumnName("model"), LoadColumn(8)]
        public string Model { get; set; }


        [ColumnName("drive"), LoadColumn(9)]
        public string Drive { get; set; }


    }
}
