// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;
using System;
using System.ComponentModel.DataAnnotations;

namespace MachineLearningProjektML.Model
{
    public class ModelInput
    {
        [Required]
        [Display(Name = "Manufacturer")]
        [ColumnName("car"), LoadColumn(0)]
        public string Car { get; set; }


        [ColumnName("price"), LoadColumn(1)]
        public float Price { get; set; }


        [Required]
        [Display(Name = "Body Type")]
        [ColumnName("body"), LoadColumn(2)]
        public string Body { get; set; }


        [Required]
        [Display(Name = "Miles driven")]
        [ColumnName("mileage"), LoadColumn(3)]
        public float Mileage { get; set; }


        [Required]
        [Display(Name = "Engine volume")]
        [ColumnName("engV"), LoadColumn(4)]
        public float EngV { get; set; }


        [Required]
        [Display(Name = "Engine type")]
        [ColumnName("engType"), LoadColumn(5)]
        public string EngType { get; set; }


        [Required]
        [Display(Name = "Registration")]
        [ColumnName("registration"), LoadColumn(6)]
        public string Registration { get; set; }


        [Required]
        [Display(Name = "Year")]
        [ColumnName("year"), LoadColumn(7)]
        public float Year { get; set; } = DateTime.Now.Year;


        [Required]
        [Display(Name = "Model type")]
        [ColumnName("model"), LoadColumn(8)]
        public string Model { get; set; }


        [Required]
        [Display(Name = "Drive type")]
        [ColumnName("drive"), LoadColumn(9)]
        public string Drive { get; set; }


    }
}
